name: CI/CD Pipeline

on:
  push:
    branches:
      - mainsss

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push backend image
        run: |
          docker build -t flask-backend ./backend
          docker tag flask-backend your_dockerhub_username/flask-backend:latest
          docker push your_dockerhub_username/flask-backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t react-frontend ./frontend
          docker tag react-frontend your_dockerhub_username/react-frontend:latest
          docker push your_dockerhub_username/react-frontend:latest

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./infra
